### ISSUE TITLE
ProtoMessage not implemented error. 

### ISSUE THREAD

**Issue by greeshma-hub** [kodandaravi724/go-distributed-system#1]
When attempting to compile the project, I encountered the following error:

```error
Error: ../../../go/pkg/mod/google.golang.org/grpc@v1.64.0/internal/status/status.go:87:20: impossible type assertion: proto.Clone(s).(*spb.Status)
	*"google.golang.org/genproto/googleapis/rpc/status".Status does not implement protoreflect.ProtoMessage (missing method ProtoReflect). 
```
Could you please provide guidance on resolving this issue?

**Comment by kodandaravi724** [comment]
This error occurs because there is a version mismatch between the google.golang.org/grpc package and the google.golang.org/genproto package, specifically with the Status proto message and the ProtoMessage interface.

To resolve the issue, please run the following commands to upgrade the dependencies:

```
go get google.golang.org/grpc@latest
go get google.golang.org/genproto@latest
go get google.golang.org/protobuf@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go mod tidy
```
This should resolve the version mismatch and fix the issue.
